# Generated by Django 4.0.6 on 2022-07-27 21:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('project_type', models.CharField(choices=[('Engineering', 'Engineering'), ('Support', 'Support'), ('HR', 'HR')], max_length=20)),
                ('added_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='%Y-%m-%d %H:%M:%S')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
